package com.fightscene.backend.domain.fighter;

public enum WeightClass {
	ATOMWEIGHT,
	STRAWWEIGHT,
	FLYWEIGHT,
	BANTAMWEIGHT,
	FEATHERWEIGHT,
	LIGHTWEIGHT,
	SUPER_LIGHTWEIGHT,
	WELTERWEIGHT,
	SUPER_WELTERWEIGHT,
	MIDDLEWEIGHT,
	SUPER_MIDDLEWEIGHT,
	LIGHT_HEAVYWEIGHT,
	CRUISERWEIGHT,
	HEAVYWEIGHT,
	SUPER_HEAVYWEIGHT
}
