CREATE TYPE user_role AS ENUM 
('USER', 'FIGHTER', 'COACH', 'GYM_ADMIN');

CREATE TYPE video_privacy AS ENUM 
('PUBLIC', 'UNLISTED', 'PRIVATE');

CREATE TYPE weight_class_enum AS ENUM (
    'ATOMWEIGHT', 'STRAWWEIGHT', 'FLYWEIGHT', 'BANTAMWEIGHT',
    'FEATHERWEIGHT', 'LIGHTWEIGHT', 'SUPER_LIGHTWEIGHT',
    'WELTERWEIGHT', 'SUPER_WELTERWEIGHT', 'MIDDLEWEIGHT',
    'SUPER_MIDDLEWEIGHT', 'LIGHT_HEAVYWEIGHT', 'CRUISERWEIGHT',
    'HEAVYWEIGHT', 'SUPER_HEAVYWEIGHT'
);

CREATE TYPE gender_enum AS ENUM ('MALE', 'FEMALE');

CREATE TYPE video_status AS ENUM 
(
 'UPLOADED_PENDING_PROCESSING',
 'READY',
 'FAILED',
 'DELETED'
);